# Generated by Django 4.1.3 on 2022-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('horario_inicio', models.TimeField(blank=True, null=True)),
                ('dia_realizar', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todo_list',
            },
        ),
    ]
